
import './globals.css'
import { monthsInBangla, getNumberInBangla } from '@/util/thoBanglaDigit'
import NavTop from './components/NavTop'
import Footer from './components/Footer'
import Provider from './context/Provider'

export const metadata = {
  title: getNumberInBangla(new Date().getDate()) + " " + monthsInBangla[new Date().getMonth()] + " " + getNumberInBangla(new Date().getFullYear()) + " ইং",
  description: 'Generated by create next app',
}
// 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-200">
        <Provider>
          <div className=' md:mx-2.5 sm:mx-1.0 mx-0 bg-white px-1.0 flex flex-col gap-3.0'>

            <NavTop />
            {children}
            <Footer />

          </div></Provider>
      </body>
    </html>
  )
}
